---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: onsdigital/dp-concourse-tools-java

inputs:
  - name: httpino

outputs:
  - name: build

run:
  path: httpino/ci/scripts/build.sh
